# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSource: 'fromFile'
    checkLatest: true
  displayName: 'Install Node.js'

- task: AzureAppServiceSettings@1
  inputs:
    azureSubscription: 'Azure subscription 1(ca3275af-1f5c-46f1-81ed-4fb8f0006566)'
    appName: 'branch-deployment-app'
    resourceGroupName: 'webapp'
